### ISSUE TITLE
The memory payload is very high?

### ISSUE THREAD

**Issue by WEIYanbin1999** [zjukg/KGTransformer#2]
When I run the pretrain code, I found the memory will be toughly full in a machine with 100+G memory. Why its CPU occupancy and memory requirements are so high? Is it normal? 
![image](https://user-images.githubusercontent.com/127707751/233532602-762c5505-64d1-4bd2-9305-2209828a56db.png)

Even I running in another machine with 30G memory, it is killed by OS because of its memory payload

**Comment by WEIYanbin1999** [comment]
Could you please provide a link for downloading the pre-trained model parameters? I think it is much helpful for us to follow your work

**Comment by YangL256** [comment]
I had the same problem. I ran it on the cloud server RTX 3090 for 11 minutes before it was killed

**Comment by WEIYanbin1999** [comment]
The memory occupancy comes from the huge 2-hop triple data dict.
