### ISSUE TITLE
Question: Where is the part of code let pretrain parameters attend to downstraming tasks

### ISSUE THREAD

**Issue by WEIYanbin1999** [zjukg/KGTransformer#3]
While I got the pretrain model, they are stored under the BIG/ dictionary.
Like this: model_layer-4_hidden-768_heads-12_seq-126_textE-cls_t0-1.0_t1-1.0_t2-1.0.ep9

However, while I run the downstreaming task code, it always mention: l_ogger      : INFO     cannot load pretrained parameters._

I found there are segment of code in downstraming task python script:
![image](https://user-images.githubusercontent.com/127707751/234364231-2c319f12-4afd-412c-8bc7-487e0b74aea0.png)

While running code in try: the pretrain_save_path is empty.  I try to modify it as model_layer-4_hidden-768_heads-12_seq-126_textE-cls_t0-1.0_t1-1.0_t2-1.0.ep6,7,8,9, but the parameter size mismatch.

So I have a question: where exactly the code utilize and load the parameters of pretrained encoder?

**Comment by WEIYanbin1999** [comment]
The problem has solved by:
![image](https://user-images.githubusercontent.com/127707751/234374987-9b43fff6-dcdf-4483-92ca-1293fdef239b.png)
However, I don't know why you padding '_delWE' to the pretrain parameter path

**Comment by YushanZhu** [comment]
Sorry for the late reply. Your way of dealing with it is okay. In fact, we also provide a file "get_pretrained_KGTransformer_parameters.py", running it can obtain the model (suffix is "_delWE") that can be loaded. Hope it will help you.

**Comment by WEIYanbin1999** [comment]
Could you release the pretrain model for reduce the
